#!/bin/bash
# converts an mp3 and image to video using ffmpeg
# https://superuser.com/a/1499738/204468
# https://stackoverflow.com/questions/62756006/how-to-create-video-from-audio-files-using-ffmpeg
# https://superuser.com/questions/843774/create-a-video-file-from-an-audio-file-and-add-visualizations-from-audio#843834

# -ab 192k
outfile="${1%.*}.mp4"
#ffmpeg -i "$1" -acodec libmp3lame -q:a 2 -map_metadata 0 $outfile
ffmpeg -i "$1" -i "$2" -c:v libx264 -tune stillimage -c:a copy "$outfile"
touch -r "$1" $outfile


ffmpeg -i input.mp3 -filter_complex \
"[0:a]avectorscope=s=640x518,pad=1280:720[vs]; \
 [0:a]showspectrum=mode=separate:color=intensity:scale=cbrt:s=640x518[ss]; \
 [0:a]showwaves=s=1280x202:mode=line[sw]; \
 [vs][ss]overlay=w[bg]; \
 [bg][sw]overlay=0:H-h,drawtext=fontfile=/usr/share/fonts/TTF/Vera.ttf:fontcolor=white:x=10:y=10:text='\"Song Title\" by Artist'[out]" \
-map "[out]" -map 0:a -c:v libx264 -preset fast -crf 18 -c:a copy output.mkv
